### PR TITLE
Modifying Module Name input To Prevent Overwriting of input() function

### PR DESCRIPTION
**Pull request by rohithvarma3000**
Hi,
I have seen issue #1102 where the input () function has been overwritten due to the input module in the brian2 folder which is causing some inconvenience to the users. So I have modified the name of the input module to input_b. I have also modified the same in the only.py folder as well.
Apart from this, I have also observed that input has been overwritten in two other python files (dev/benchmarks/openmp/STDP_standalone.py and brian2/tests/test_GSL.py) as well. I have the modified the name in those files as well to avoid other issues in the future.

### CODE REVIEW

**Comment by rohithvarma3000** [comment]
Do you think there are other files where this file name change should be made to get to ensure that code works??

**Comment by rohithvarma3000** [comment]
Do you think there are other files where this file name change should be made to ensure that code works??

**Comment by rohithvarma3000** [comment]
Hello @mstimberg,
I have identified more places where 'input' is being used as file, folder and variable name. I have appropriately modified all of those that I could find. Do you think there are other places that I need to make a change to ensure that the code continues to work?

**Comment by mstimberg** [comment]
Apologies for being a bit slow responding to this. We need to be careful with this issue because it fixes something that is not a very big problem: if you want to use a shadowed `input()` you will get an error, and there are straightforward workarounds. On the other hand, renaming the `input` package can potentially break a user's script if they do something like `from brian2.input import PoissonGroup` which would be a violation of our [Compatibility policy](https://brian2.readthedocs.io/en/stable/introduction/compatibility.html). So it might actually be the best solution to not fix this issue but instead to clearly document it (and to recommend using `from brian2.only *` for users worried about shadowing things). Again, @thesamovar might have an opinion on this.

Note that we will probably do a bigger rework of the import framework as part of #1217

**Comment by rohithvarma3000** [comment]
Hello @mstimberg,
I understand that backward compatibility will be a huge problem if we try to change the name of the folder. I think it will be better to avoid fixing this issue and rather document this behavior. Where do you think we should add this in the documentation ?
I have also observed that `input` is being used as a variable in some python files. I think that this could lead to confusion to new users and developers as well. Do think it would be a good idea to change these variable names to avoid this confusion? (I don't think changing these variable names will affect the backward compatibility of brian2)

**Comment by mstimberg** [comment]
I think the page about "importing Brian" would be the best place in the documentation: https://brian2.readthedocs.io/en/stable/user/import.html

> I have also observed that `input` is being used as a variable in some python files. I think that this could lead to confusion to new users and developers as well. Do think it would be a good idea to change these variable names to avoid this confusion? (I don't think changing these variable names will affect the backward compatibility of brian2)

I'd be happy with any changes that changes the name of `input` to something else in the code (could even be something somewhat ugly like `inp`, but in cases where it makes sense could also be a more meaningful name about the type of input, say `spike_input`). If it is only used internally in a function (or in an example script) and not e.g. an argument of a function or an object attribute, then it should not be a problem for backwards compatibility.

**Comment by rohithvarma3000** [comment]
Ok, I will work on these two parts.

**Comment by mstimberg** [comment]
Superseded by #1270 and #1271.

**Pull request closed without merging**
