### PR TITLE
Implementiation of Spreizer_et_al_2019: an anisotropic network

### PR DESCRIPTION
**Pull request by arashgmn**
Reproduction of Fig. 2 (b and c) of Spreizer et al. 2019 in Brian: 

Spreizer S, Aertsen A, Kumar A. From space to time: Spatial inhomogeneities lead to the emergence of spatiotemporal sequences in spiking neuronal networks. PLOS Computational Biology. 2019;15(10):e1007432. doi:10.1371/journal.pcbi.1007432

Requirements:

- Brian
- numpy 
- matplotlib
- noise: For setting up the Perlin landscape.

Happy new year and merry Christmas!

### CODE REVIEW

**Comment by mstimberg** [comment]
Hi @arashgmn, many thanks for this contribution! I'll need a bit of time to look through it in detail and figure out the best way to integrate the generated figures, but it should be a very nice addition to our docs :pray:

**Comment by mstimberg** [comment]
Thanks again for the contribution and apologies that it took me ages to actually look into this in detail. I spent an unreasonable amount of time to get this to  be more similar to the figure from the original paper. But of course, thanks to your animation, it is much better than the original plot now :smile: 

Here's what it looks like now:
anim

Are you happy with my code changes and the new figure? Apologies for the re-formatting, it makes the changes harder to see. I realized too late that my editor was configured to run the black formatter over everything. I also tok the liberty to copy the pre-generated noise files directly here, this should make it easier for anyone using the files.

**Comment by arashgmn** [comment]
Hi @mstimberg,
Thanks for taking care of the plots! They look amazing and I'm totally happy with the changes :)

**Review by arashgmn — COMMENTED** [review]
All seem good to me!

**Review by arashgmn — COMMENTED** [review]
All seem good to me!

**Review by mstimberg — APPROVED** [review]
Good to go :tada: 
Thanks again!

**Pull request merged**
