### PR TITLE
[MRG] Fix OpenMP profiling

### PR DESCRIPTION
**Pull request by mstimberg**
This has two small fixes to the OpenMP support: in the synapses template, every code that used a scalar variable incorrectly triggered the use of the single-thread code (affecting the post code in STDP). The second fix is to use `omp_get_wtime` instead of `std::clock` to count runtimes, this avoid the weird profiling results and makes it unnecessary to divide by number of threads etc.

It's all fairly simple changes and it would be ready to merge but the OpenMP test now apparently no longer compiles on Windows. @thesamovar could you have a look at it? It does not give any helpful output in the log and trying to figure this out in my Windows VM is way too annoying for a Friday evening...

### CODE REVIEW

**Comment by thesamovar** [comment]
Will do!

**Comment by thesamovar** [comment]
Ah, does this solve some of the issues that people have been telling us about recently?

**Comment by mstimberg** [comment]
Only very partially (but the standard profiling_summary can now be used to look at issues in more detail): the synaptic post code in STDP was not parallelized and that is fixed with the first commit, so this will scale nicely now with more threads. For the pre pathway, it is still completely sequential, though. Same for the threshold, which can also take a fair amount of time.

**Comment by thesamovar** [comment]
Runs fine here, and appears to be building fine on AppVeyor now...

**Comment by thesamovar** [comment]
Ah no, it's not. OK, looking into it.

**Comment by thesamovar** [comment]
OK the problem was just that in OpenMP 2.0 (the version with MSVC) you can't use unsigned ints, but in 3.0 (which gcc has) you can. Changed this and should be fine now.

**Comment by thesamovar** [comment]
Also good to merge as far as I'm concerned.

**Comment by mstimberg** [comment]
Thanks for figuring this out, I'm merging it now.

**Pull request merged**
