### PR TITLE
[WIP] Various changes for 2.0RC release

### PR DESCRIPTION
**Pull request by thesamovar**
This branch and PR for any little changes to e.g. docs etc. that we want to make before releasing 2.0rc.

### CODE REVIEW

**Comment by thesamovar** [comment]
Do you think we should put a warning about the poor RNG for cpp_standalone? For example, we could make it so that if ``rand()`` is called during a ``cpp_standalone`` run it logs a warning. (We could this by making some attribute of the ``rand`` ``Function`` implementation for cpp_standalone be a computed attribute that raises a warning.) We could also put a warning in the docs.

**Comment by thesamovar** [comment]
Added a fix and improvements for #670.

**Comment by mstimberg** [comment]
I fixed a few small things in the docs and added some release notes -- feel free to add to them or correct things you are not happy with!

**Comment by thesamovar** [comment]
Looks good to me!

**Comment by mstimberg** [comment]
I think we agreed about all the changes in this PR and all tests pass, I'll go ahead with the merge.

**Pull request merged**
