### PR TITLE
Setting a warning if threshold but no reset/refactor

### PR DESCRIPTION
**Pull request by rohithvarma3000**
Hi @mstimberg,
I have made the changes that you had suggested to the `NeuronGroup.__init__` function in the `NeuronGroup` class in the issue #1169 .

### CODE REVIEW

**Review by mstimberg — CHANGES_REQUESTED** [review]
Thanks for the PR! There are a few issues that we'd need to fix before merging, though:
1. Could you use the logging/warning infrastructure instead of print (i.e. `logger.warn`, see https://brian2.readthedocs.io/en/stable/developer/guidelines/logging.html)?
2. There's a `{}` placeholder in the text but it does not seem to be filled with anything.
3.  Finally, it would be great to have a test that shows that it actually works as intended.  You can use [`catch_logs`](https://brian2.readthedocs.io/en/stable/developer/guidelines/logging.html#testing-log-messages) to test for warning messages. Please do not test for the exact text of the warning, testing that a warning of the correct type is raised is enough. If you are having issues with writing/running the tests, please have a look at https://brian2.readthedocs.io/en/stable/developer/guidelines/testing.html – or let me know and I can handle the test part.

There's also a typo in "argumnet".

**Comment by rohithvarma3000** [comment]
Hello @mstimberg,
I apologize for the typos that I have made. I made the changes that you have requested me to make. Apart from that, I have added the test for this warning message under the `test_threshold_rest()` function under `test_neurongroup.py` file as well.

**Comment by rohithvarma3000** [comment]
Hello @mstimberg,
I apologize for the typos that I have made. I made the changes that you have requested me to make. In the warning message, I have included the number of neurons just to make it easier for the users to find the `NeuronGroup` where the warning is arising from.
Apart from that, I have added the test for this warning message under the `test_threshold_rest()` function under `test_neurongroup.py` file.

**Comment by rohithvarma3000** [comment]
Hello @mstimberg,
I apologize for the typos that I have made. I made the changes that you have requested me to make. In the warning message, I have included the number of neurons just to make it easier for the users to find the `NeuronGroup` where the warning is arising from.
Apart from that, I have added the test for this warning message under the `test_threshold_reset()` function under `test_neurongroup.py` file

**Review by mstimberg — CHANGES_REQUESTED** [review]
Thanks for the changes and adding a test. Unfortunately the test is failing at the moment. I think the best approach would be to use a `name_suffix` for the warning (see the [documentation](https://brian2.readthedocs.io/en/stable/reference/brian2.utils.logger.BrianLogger.html#brian2.utils.logger.BrianLogger.warn)) and check for this suffix with `endswith`.
I'd also replace the number of neurons with the `name` of the `NeuronGroup`, i.e. `self.name`.

**Review by mstimberg — APPROVED** [review]

**Comment by mstimberg** [comment]
Thanks again for the contribution. I made some minor changes (mostly code formatting) and merged latest master into this branch. I will merge as soon as the test suite passes.

**Pull request merged**
