### PR TITLE
`TimedArray`s that support a temporal offset

### PR DESCRIPTION
**Pull request by DylanMuir**
Added an argument to `TimedArray`, such that an array of values can be shifted in time to begin at a fixed temporal offset. When continuing a simulation from t > 0, one would like to provide a new input signal as a `TimedArray`. Without the temporal offset, the `TimedArray` needs to be padded out to the current simulation time.

### CODE REVIEW

**Comment by mstimberg** [comment]
Thanks for the pull request! I did not look at it in detail yet, but let's first make sure that I understand what problem it is solving given that in Brian 2 a `TimedArray` is used as a function of time. With the standard `TimedArray`, you can shift things around in time like this:
```Python
ta = TimedArray(...)
offset = 100*ms
neurons = NeuronGroup(..., '''... ta(t - offset)...''')
```
What kind of model do you have in mind where this would not be enough?

**Comment by DylanMuir** [comment]
Hi @mstimberg, that's true you could modify the equations in that way.

When generating inputs to the network, it would be nice to provide an input displaced in time without having to modify the network namespace. Or if two inputs were provided with different temporal offsets, etc... It's nice to decouple the input signals from the network equations.

**Comment by mstimberg** [comment]
I'm very sorry for not having been responsive on this pull request... There are some issues in the code that needs fixing (as indicated by the failed tests), but before getting to this I want to be sure we really want this feature. When we implemented the `TimedArray` as an input of time, we had situations like offsets or periodic stimulation in mind. We thought that it would be better to represent such details explicitly in the equations instead of adding options to the `TimedArray` initializer because it is 1) more explicit in the model equations which are the core part of the model description and 2) it gives you a lot of flexibility (e.g. the offset could be a global constant, a constant per neuron, a function of something, etc.). So I'm still not really convinced that we need this special case as an additional feature. @thesamovar , @romainbrette : what do you think?

On the other hand, the use case in your initial comment is certainly a valid one and it might be a good idea to make these kind of situations easier to handle. A simple thing I could think of would be to give access to a variable `start_t` that stores the start time of the current run, so that you could use that variable as an offset.

**Comment by thesamovar** [comment]
I'm also not sure we need a special case. Your ``ta(t-offset)`` and ``offset`` is a variable seems to work perfectly well as far as I'm concerned. The ``offset`` could also be a variable of the group, for example.

**Comment by DylanMuir** [comment]
From a model design cleanliness point of view, I think it would be beneficial to decouple the model equations from the input signals.

**Comment by mstimberg** [comment]
Thanks again for your contribution, but I'm closing this pull request for now as I think the core developers agree that this is not a feature we want right now. I'll open an issue about the `start_t` thing, though, it could be interesting to have access from within the equations to the simulation start/end time.

**Pull request closed without merging**
