### PR TITLE
[MRG] Improve stochastic parsing

### PR DESCRIPTION
**Pull request by mstimberg**
This branch contains a few improvements for dealing with complex, in particular stochastic, equations. In `Expression.split_stochastic`, the use of sympy's `expand` could result in very big strings that made everything slow and could even lead to memory errors (for the example provided on the mailing list https://groups.google.com/d/topic/brian-development/fL8wfggCMrw/discussion it resulted into a > 2MB string...). I removed the `expand` and also replaced the quite demanding `match` by a simple `collect`, it seems to work fine. The branch also contains a few smaller improvements that should avoid a few unnecessary sympy operations.

### CODE REVIEW

**Comment by ttxtea** [comment]
Hi,

Concerning the separation of the eq_expression into drift and diffusion part. I think this is a function of general interested. For example to extract the diffusion matrix from a brian2.Equations SDE once can just use:

Smat = [[sympy.S(j[1]).coeff(k)
               for k in sde.stochastic_variables] 
              for j in sde.eq_expressions]

this would not need a simplification of the expression. I am not sure how it is done at the moment. To extract the drift part I just substitute all stochastic_variables with 0 :D. Should one maybe add two function for that?

by the by: I worked with this branch a bit more - no hickups sofar.

**Comment by mstimberg** [comment]
I'm not sure that this is something that many users need, after all you provide the equations yourself :) But in principle you can already use the function that Brian uses internally:
```Python
>>> eqs = Equations('dv/dt = -v/tau + xi*tau**-0.5 : 1')
>>> eqs['v'].expr.split_stochastic()
(-v/tau, {'xi': tau**(-0.5)})
```
It's not that different from `coeff`, but it will raise an error if the equation contains `1/xi` or `xi**2` or something like that, while `coeff` would just return you nothing for `xi`, I think.

**Comment by thesamovar** [comment]
I'm happy with the changes if you're ready to merge.

**Comment by mstimberg** [comment]
Ready to merge I am!

**Comment by thesamovar** [comment]
Going Yodic are we?

**Comment by mstimberg** [comment]
It's Friday night and all that :)

**Pull request merged**
