### PR TITLE
Improve `Variable` objects

### PR DESCRIPTION
**Pull request by mstimberg**
This makes sure that all `Variable` objects, including `Constant` and `AttributeVariable` have an `owner` attribute, making it easier to check for the owner of variables in a general way. Also adds a `variables_by_owner` utility function that returns all variables that "belong" to a group:
```Python
from brian2 import *
from brian2.core.variables import variables_by_owner

S = Synapses(...)

# get all the synaptic variables
syn_vars = variables_by_owner(S.variables, S)
# get all the pre-synaptic variables
pre_vars = variables_by_owner(S.variables, S.source)
```

From my side: ready-to-merge

### CODE REVIEW

**Comment by thesamovar** [comment]
All good and tests pass. Shame about the drop of 0.01% in coverage though. ;)

Merging now.

**Comment by thesamovar** [comment]
Can we also merge this into device_correctness so that @tnowotny can use it in brian2genn?

**Comment by mstimberg** [comment]
We already merged device_correctness into master, so I guess that's what he should use now.

**Comment by thesamovar** [comment]
I was going to say yes but the loop-invariant stuff is a problem but I'm just about to merge the fix for that into master too, so not necessary. :)

**Comment by mstimberg** [comment]
Great :)

**Pull request merged**
