### PR TITLE
[MRG] Rename the `pre` and `post` keyword arguments to `on_pre` and `on_post`

### LINKED ISSUE #582: Are pre and post keyword arguments in Synapses confusing?
@romainbrette

### PR DESCRIPTION
**Pull request by mstimberg**
`pre` and `post` still work, but raise a warning
Closes #582 

Should be good to merge.

### CODE REVIEW

**Comment by thesamovar** [comment]
Checks passing and I'm happy with the change so merging now. We should make sure to put a big note about this in the change notes because it's a big change to syntax that will cause a lot of old scripts to issue warnings.

**Comment by thesamovar** [comment]
Wait there are some conflicts that need to be resolved before it can be merged?

**Comment by mstimberg** [comment]
> Wait there are some conflicts that need to be resolved before it can be merged?

Ah, right, I'll do this. I fixed a few examples in the master branch (something that I thought I did in the synapses PR before but apparently I did not) and these examples have changed here as well.

**Comment by mstimberg** [comment]
I take the liberty to merge this even though the tests have not yet run through after the merge from master. The merge did only touch examples, though, and those are not tested by the test suite anyway.

**Pull request merged**
