### PR TITLE
[MRG] Don't info the method choice if linear and time<2s (fixes #663)

### LINKED ISSUE #663: Update examples to specify method to avoid info notices?
Or don't show method choice for method=linear?

### PR DESCRIPTION
**Pull request by thesamovar**
We can still discuss this but writing this only took a moment so thought I should just throw it out there as an option.

### CODE REVIEW

**Comment by thesamovar** [comment]
Oh it fails the test designed to check that the log entry is there. :)

**Comment by mstimberg** [comment]
I am still not sure about this... The reason why I think it makes sense to have the message on the screen is that we want to be explicit and do not hide an important decision like the numerical integration method from the user. It might well be that some changes in Brian (or sympy) will change what method is selected, and this should be obvious for the user. I know that you argue that `linear` is the best choice and it is therefore not necessary to mention it, but we had issues like the code in #626 which fail with linear integration and work fine with euler.

But just visually it makes the output look noisy and I guess users quickly start to ignore it, therefore they won't notice if it changes, anyway. On the other hand, it might motivate users (and us, for the examples) to explicitly specify the integration method. The advantage would be that 1) results should be reproducible across Brian/sympy versions and 2) if you change something in your model so that it is no longer linear, you'll have to make an explicit choice what method to use instead of just falling back to euler.

@romainbrette what do you think about this?
As a quick background in case you did not follow this dicussion: in current master, creating a `NeuronGroup` without explicitly setting `method=...`, you'll get an INFO message like this:
```
INFO       No numerical integration method specified for group 'neurongroup', using method 'linear' (took 0.52s). [brian2.stateupdaters.base.method_choice]
```
(the time is mentioned because the linear method can sometimes take very long for complex equations and it is not always obvious to the user what took so long). This pull request is about removing the message if the method is "linear" (since it is the best method possible in general) and if it took less than 2s (i.e. it is not prohibitively costly to do the symbolic solution).

**Comment by thesamovar** [comment]
Even taking #626 into account I'd still argue that linear is still the in-principle best solution and so we don't need to notify the user. I don't think anyone would guess for example that if it said the integration method was linear, that that might mean it was wrong! That's a bug and not a fault with the way we log information, I'd say.

We should really try to find some way to address #626 by the way. I'd completely forgotten about that.

**Comment by mstimberg** [comment]
> Even taking #626 into account I'd still argue that linear is still the in-principle best solution and so we don't need to notify the user. I don't think anyone would guess for example that if it said the integration method was linear, that that might mean it was wrong! That's a bug and not a fault with the way we log information, I'd say.

I'm not sure. If you get NaNs in your integration and you have a message that tells you that linear integration was chosen for you automatically, you might be more likely to try out a different integration method, no? Maybe we should "train" our users to always switch on the debug mode if something is going wrong, though...

However: if we fix #554 and the warning for an unstable integration includes the chosen method, than probably all this would be less of an issue. I'd probably then have the info message only appear with a time limit, independent of the chosen integration method.

**Comment by thesamovar** [comment]
Last suggestion sounds perfect to me! Seems like the best way to transmit information like that to the user is if we notice something has gone wrong.

**Comment by mstimberg** [comment]
I had a discussion about this with @romainbrette and our consensus was:
* having these messages all the time is not a big deal since you can switch them off, either by specifying the integration method manually, or by using `BrianLogger.suppress_name('method_choice')` (if there's demand for this, we could also turn this into a preference)
* it seems to be justified to show these messages, given that this is the only choice in Brian that we make for the user (apart from the codegen target, but this is more technical)
* switching the messages off for certain methods and/or timing feels a bit arbitrary (why is 1.5s fine, but 2.1s isn't) and will make the output non-deterministic

I know that with the last point I am somewhat contradicting my previous comment, but I feel that it is most in the "spirit of Brian" to never hide an important detail like the integration method.

So here's a proposal: let's leave the output on for all methods and without the time limit (as it is in current master) for now, and re-evaluate before the final release of 2.0. What do you think?

**Comment by thesamovar** [comment]
OK if you both agree to leave the messages I'm happy to be outvoted. ;)

We should probably update the examples though? Maybe not necessary (and definitely not for RC).

**Comment by mstimberg** [comment]
> We should probably update the examples though? Maybe not necessary (and definitely not for RC).

Right, I'll just do it -- it does not trigger the test suite so it will not delay anything.

**Comment by mstimberg** [comment]
I think we decided to actually not do this, and we've adapted the examples so that they don't show the INFO message anymore. I'll therefore go ahead and close this PR.

**Pull request closed without merging**
