### PR TITLE
[Gsoc 2020]Add example for printing text based progress bar in standalone mode in documentation

### PR DESCRIPTION
**Pull request by rahuliitg**
you can try running this example by adding this piece of code in standalone.py in the examples folder

#1162

### CODE REVIEW

**Comment by rahuliitg** [comment]
@mstimberg please check this example...

**Comment by mstimberg** [comment]
The example is very neat! I did not look at the code in detail yet, but I noticed that the branch is built on top of the commits for the time format changes. Could you separate the two things? I.e., either rebase this branch on top of current master (and then "force push"), or create a new branch only with the last commit (i.e. open a new PR).

**Comment by rahuliitg** [comment]
@mstimberg I've created a new branch.

**Comment by rahuliitg** [comment]
should I close this pull request?

**Comment by mstimberg** [comment]
> should I close this pull request?

Yes, I'll close it.

**Pull request closed without merging**
