### PR TITLE
[MRG] Synapse to synapse fix

### PR DESCRIPTION
**Pull request by mstimberg**
I realized that our changes to synapse creation did actually break the "synapse-to-synapse" connections we need for the astrocytes project. We had a test for that, but that test used 1-to-1 connections everywhere so the use of incorrect indices went unnoticed. The change is to not rely on the pre-defined arrays of `arange(N)` that every `NeuronGroup` has but instead create them on the fly -- performance-wise it should not change anything (addition of two variables instead of an array lookup), except maybe for numpy (because we now do an explicit check instead of relying on an automatic `IndexError` -- however, this has the advantage that the error message is now clearer and consistent with weave/cython). I did not notice anything significant in some quick testing.

The names `all_pre` and `all_post` are not ideal, maybe we should also use the opportunity to rename them to something more understandable...?

### CODE REVIEW

**Comment by thesamovar** [comment]
Looks good to me. What would you prefer to ``all_pre`` and ``all_post``? I think they're but but I don't mind changing them unless that might break other packages code (e.g. genn).

**Comment by mstimberg** [comment]
> What would you prefer to all_pre and all_post?

I don't have a really good idea, the difference in the code is that `i` and `j` refer to the variables as used by a user (e.g. when connecting to from `group[5:]`, `i == 0` would correspond to `group[5]`), where `all_pre` and `all_post` refer to the actual indices into the array (i.e. `5` for the above example). Maybe `real_pre_idx`/`actual_pre_idx`/`full_pre_ix` or something like that?

> I think they're but but I don't mind changing them unless that might break other packages code (e.g. genn).

I think it can't break anything that we did not already break with the switch to the generator-based approach...

**Comment by thesamovar** [comment]
Ah I see. I don't really like real/actual/full in this case, but not quite sure why. How about ``raw_idx_pre``, etc.? Or ``raw_offset_pre``?

**Comment by mstimberg** [comment]
"Raw" sounds good to me, I would rather call it index and not offset. I'll make this change.

**Comment by mstimberg** [comment]
I went for `_raw_pre_idx` instead of `_raw_idx_pre` because this was more consistent with other variables ending in `_idx`.

**Comment by thesamovar** [comment]
Great - good to merge.

**Pull request merged**
