### PR TITLE
Function improvements + PoissonInput

### LINKED ISSUE #380: Revise function-specific namespace mechanism
Some functions need an additional namespace, for example `TimedArray` needs to refer to the values. This is currently done using some `#define` hackery for weave and we don't have any solution for Cython yet.

I think we need a more principled approach, e.g. instead of relying on a `#define` we could have the renderer write the function call with all the namespace values (e.g. alphabetically ordered) as additional arguments.

### PR DESCRIPTION
**Pull request by mstimberg**
This branch adds several improvements  to the function system and closes #380, #366, #373, #221. Functions can now depend on other functions and the namespace is passed to functions using global variables instead of via `#define` hackery (we are actually not using `hash_define` anywhere anymore, maybe we should remove it?). There are also two new classes: `BinomialFunction` (with fixed n and p) and `PoissonInput` (also fixed number of inputs and rates) which uses the former.

This is basically done from my side, I'm not too sure about the placements in the package hierarchy (the binomial is in `brian2.utils.binomial` and `PoissonInput` is in `brian2.groups` even though it isn't a group).

### CODE REVIEW

**Comment by mstimberg** [comment]
Oh, I forgot to mention: this branch includes commits from the `poisson_input` branch which is now obsolete (I therefore deleted it on github).

**Comment by thesamovar** [comment]
This looks great. I actually ran the tests on my computer and then realised that I didn't need to thanks to AppVeyor! :)

For the packages, how about we have a new ``brian2.random`` package and put binomial there? At the moment it will be the only thing but it's going to happen at some point. Alternatively, we could have a new package that has slightly more general scope and we could binomial, poisson input, timedarray, etc. there. I'm still not very happy with timedarray being in utils. I originally thought of utils as being independent stuff that wouldn't rely on the rest of the brian2 package.

Maybe let's just leave it for the moment and think about having a package reorganisation at some point?

I'm happy for this branch to be merged if you're done with it?

**Comment by mstimberg** [comment]
> For the packages, how about we have a new brian2.random package and put binomial there? At the moment it will be the only thing but it's going to happen at some point. Alternatively, we could have a new package that has slightly more general scope and we could binomial, poisson input, timedarray, etc. there. I'm still not very happy with timedarray being in utils. I originally thought of utils as being independent stuff that wouldn't rely on the rest of the brian2 package.

I agree, I also would like to find a better place for `timedarray`. How about something like `brian2.input`, `brian2.stimulus` (or `stimuli`), ...? In Brian 1 there was a module called `directcontrol`, though I never found that very clear. It could be a place for `SpikeGeneratorGroup`, `PoissonGroup`, `PoissonInput`, `TimedArray` and `BinomialFunction` -- but I'd be happy to leave the first two in `brian2.groups` as well, after all they are proper groups.

Apart from the reorganisation, I'm finished with the branch. But it would probably be a good time to move things around.

**Comment by thesamovar** [comment]
I like ``brian2.input``, shall we go with that?

**Comment by mstimberg** [comment]
> I like brian2.input, shall we go with that?

I'm happy with that. Do you think it should include `SpikeGeneratorGroup` and `PoissonGroup` as well?

**Comment by thesamovar** [comment]
I would say yes.

**Comment by mstimberg** [comment]
Ok, fine with me, I'll move things around accordingly.

**Comment by mstimberg** [comment]
Ok, all done. Let's maybe wait again for the tests (they are not on the last commit, the last commit only adds docstrings) to complete and then merge.

**Comment by mstimberg** [comment]
Tests pass, feel free to merge if you are fine with everything.

**Pull request merged**
