### PR TITLE
[MRG] Better unit errors

### PR DESCRIPTION
**Pull request by mstimberg**
This should give significantly better error messages for unit mismatches, e.g. instead of
```Python
>>> 3*mV + 1*mV + 3*ms
...
DimensionMismatchError: Addition, dimensions were (m^2 kg s^-3 A^-1) (s)
```
you'll now get
```Python
DimensionMismatchError: Cannot calculate 4. mV + 3. ms, units do not match (units are volt and second).
```

Instead of 
```Python
DimensionMismatchError: exp, dimensions were (m^2 kg s^-3 A^-1) (1)
```
you get
```Python
DimensionMismatchError: exp expects a dimensionless argument but got -70. mV (unit is volt).
```

and instead of
```Python
>>> G = NeuronGroup(1000, 'v : volt')
>>> G.v = np.arange(1000)*mA
...
DimensionMismatchError: Incorrect units for setting v, dimensions were (A) (m^2 kg s^-3 A^-1)
```
you get
```Python
DimensionMismatchError: v should be set with a value with units volt, but got [ 0.     0.001 ...,  0.998  0.999] A (unit is amp).
```

This is finished and in principle ready-to-merge but I did not yet check in detail all the error messages yet.

### CODE REVIEW

**Comment by thesamovar** [comment]
Nice!

**Comment by mstimberg** [comment]
I made some further changes, and fixed some missing unit checking when directly calculating with `VariableView` objects (i.e. `G.v` instead of `G.v[:]` etc.). I found one bug in the unit system that I find no way around: in-place modification of a pure numpy-array does no unit checking, i.e.:
```Python
x = np.array(...)
x += q
```
works for any quantity `q`. Maybe I'm missing something here, but none of the usual mechanisms (`__add__`, `__radd__`, `__array_prepare__`, `__numpy_ufuncs__`...) gets called in the `Quantity` class so I don't see what we can do here. Maybe I should ask this with a minimal example on stackoverflow...

**Comment by mstimberg** [comment]
I used a little script to generate a bunch of error messages (https://gist.github.com/mstimberg/9c1706e9af67154c03fc). If they look all good to you, then this is ready to merge:

Expression/Statement | Error message
-------------------- | -------------
`3*mV+5*mA` | `Cannot calculate 3. mV + 5. mA, units do not match (units are volt and amp).`
`sin(5*mV)` | `sin expects a dimensionless argument but got 5. mV (unit is volt).`
`np.where(True, (np.arange(10)*mV), (np.arange(10)*mA))` | `x and y need to have the same dimensions (units are volt and amp).`
`3*mV -1` | `Cannot calculate 3. mV - 1, units do not match (units are volt and 1).`
`1 - 3*mV` | `Cannot calculate 1. - 3. mV, units do not match (units are 1 and volt).`
`2 ** (3*mV)` | `Cannot calculate 2 ** 3. mV, the exponent has to be dimensionless (unit is volt).`
`Quantity(2, force_quantity=True) ** (3*mV)` | `Cannot calculate 2. ** 3. mV, the exponent has to be dimensionless (unit is volt).`
`3 % (3*mV)` | `Cannot calculate 3 remainder 3. mV, the units do not match (units are 1 and volt).`
`3*mV % 5*mA` | `Cannot calculate 3. mV % 5, units do not match (units are volt and 1).`
`max(1*mV, 2*mV, 3*mA)` | `Cannot perform comparison 3. mA > 2. mV, units do not match (units are amp and volt).`
`max([1*mV, 2*mV, 3*mA])` | `Cannot perform comparison 3. mA > 2. mV, units do not match (units are amp and volt).`
`3*mV < 5*mA` | `Cannot perform comparison 3. mV < 5. mA, units do not match (units are volt and amp).`
`3*mV >= 5*mA` | `Cannot perform comparison 3. mV >= 5. mA, units do not match (units are volt and amp).`
`3 >= 5*mA` | `Cannot perform comparison 5. mA <= 3, units do not match (units are amp and 1).`
`3*mV >= 5` | `Cannot perform comparison 3. mV >= 5, units do not match (units are volt and 1).`
`5*second == 3*volt` | `Cannot perform comparison 5. s == 3. V, units do not match (units are second and volt).`
`5*second != 3*volt` | `Cannot perform comparison 5. s != 3. V, units do not match (units are second and volt).`
`python_sum([3*mV, 4*mV, 5*mA])` | `Cannot calculate 7. mV + 5. mA, units do not match (units are volt and amp).`
`hypot(3*um, 4*um)` | `Both arguments for "hypot" should be dimensionless but first argument was 3. um (unit is metre).`
`hypot(3*um, 4)` | `Both arguments for "hypot" should be dimensionless but first argument was 3. um (unit is metre).`
`hypot(3, 4*um)` | `Both arguments for "hypot" should be dimensionless but second argument was 4. um (unit is metre).`
`myfunc(3*mA, 0)` | `Function "myfunc" expected a quantitity with unit volt for argument "x" but got 3. mA (unit is amp).`
`myfunc(3*mV, 1*ms)` | `Function "myfunc" expected a quantitity with unit 1 for argument "y" but got 1. ms (unit is second).`
`myfunc(3*mA, 1*ms)` | `Function "myfunc" expected a quantitity with unit 1 for argument "y" but got 1. ms (unit is second).`
`myfunc(3*mV, 1)` | `The return value of function ""myfunc" was expected to have unit amp but was 1. ms (unit is second).`
`G.x = 3*mV` | `x should be set with a dimensionless value, but got 3. mV (unit is volt).`
`G.x = np.arange(10)*mV` | `x should be set with a dimensionless value, but got [ 0.  1. ...,  8.  9.] mV (unit is volt).`
`G.y = 2*mA` | `y should be set with a value with units volt, but got 2. mA (unit is amp).`
`G.y = 2` | `y should be set with a value with units volt, but got 2 (unit is 1).`
`G.y = np.arange(10)*mA` | `y should be set with a value with units volt, but got [ 0.  1. ...,  8.  9.] mA (unit is amp).`
`G.y = np.arange(10)` | `y should be set with a value with units volt, but got [0 1 ..., 8 9] (unit is 1).`
`G.y += G.x` | `Cannot calculate [ 0.  0. ...,  0.  0.] V + [ 0.  1. ...,  8.  9.], units do not match (units are volt and 1).`
`G.y = G.x + G.y` | `Cannot calculate [ 0.  0. ...,  0.  0.] V + [ 0.  1. ...,  8.  9.], units do not match (units are volt and 1).`
`G.x += G.y` | `Cannot calculate [ 0.  0. ...,  0.  0.] V + [ 0.  1. ...,  8.  9.], units do not match (units are volt and 1).`
`G.x = G.x + G.y` | `Cannot calculate [ 0.  0. ...,  0.  0.] V + [ 0.  1. ...,  8.  9.], units do not match (units are volt and 1).`
`x = np.arange(3)*mV; x += 1` | `Cannot calculate ... += 1, units do not match (units are volt and 1).`
`x = np.arange(3)*mV; x += 1*mA` | `Cannot calculate ... += 1. mA, units do not match (units are volt and amp).`
`S = Synapses(G, G, "", pre="x+=1", delay=5*amp)` | `Delay has to be specified in units of seconds but got 5. A (unit is amp).`
`G2 = NeuronGroup(3, "dv/dt = -v/(10*ms) : 1 (unless refractory)", refractory=5*amp)` | `Refractory period has to be specified in units of seconds but got 5. A (unit is amp).`

**Comment by thesamovar** [comment]
The messages look fantastic. I think this was really worth doing and will be great for users. Merging now.

**Pull request merged**
