### PR TITLE
[MRG] Fix various inefficiencies

### PR DESCRIPTION
**Pull request by mstimberg**
Ok, this one deserves slightly more discussion. It fixes a few "low-hanging fruits" for performance, hopefully it should now compare better against Brian 1. Nothing too controversial here, the changes are:
* As mentioned previously, the way the clock was accessed in `Network.run` was far from optimal. I changed it in a way that takes some logic out of the `Clock` class and puts direct access to the variables in `Network.run`. This makes the code somewhat less readable but I think it is justified here since `Clock.running` and `Clock.tick` were only ever used from within the runtime `Network.run` function, standalone had to do something else. So not having this in `Clock` but instead in `Network.run` seems like the sensible choice, instead of having very runtime specific code in the `Clock` class.
* During import, all the templates for all code generation targets were loaded into memory, which took a significant amount of time, I changed it so that they are now loaded on demand only.
* There was one left-over call where `NeuronGroup` tried to run `before_run` in its constructor, which only worked if the namespace was already complete. In line with the changes for the state updater/thresholder/resetter in the `optimize_before_run` branch we did earlier, I removed this.
* For every expression that went through code generation, we went through the variables dictionary, noted all the name translations (e.g. `acos` to `arccos`) and replaced them in the expression. We now create a dictionary of name translations when we create the `CodeGenerator` object.
* We were still using sympy's `simplify` function, which tries out all kind of simplifications and takes quite a long time. I replaced this by a few specific simplifications that for the linear equations of the CUBA example lead to basically the same result but take much less time.

Looking at the profiling output I don't see anything obvious to improve any more. The only significant improvements that I could think of would take more thought, e.g. things that optimize the whole run loop (special case a single clock or pre-calculate a completely fixed schedule, say. `clock1, clock2, clock1, clock2, ...`, instead of checking things on a per-timestep basis, merging code objects if there is nothing in between them, etc.).

If you can't think of any more obvious inefficiencies (the synapses discussion aside), then this is ready to merge from my side.

### CODE REVIEW

**Comment by thesamovar** [comment]
OK, great. In terms of performance for the numpy codegen target, Brian 2 is almost as good for low N and better for high N than Brian 1 (for the case of NeuronGroup only, no refractoriness, Euler integration forced). Here's the plot:

figure_1

And here's with refractoriness switched back on - also great.

figure_1

However, if I put ``SpikeMonitor`` into that simulation, the situation changes a lot. I guess this is because ``SpikeMonitor`` is accessing ``t`` in the old way? Perhaps it's worth considering a deeper change to the way state variables are accessed by templates in runtime? Not sure if that's the difference or not, but if it's really the case that each access to these variables is slowing things down this much then it's problematic.

figure_1

Next, here's a version with synapses included. Note that in Brian 1 we've got Connection and in Brian 2 we've got Synapses. Brian 2 is using the Cython SpikeQueue. Brian 1 is storing a weight matrix which Brian 2 is not doing, however Brian 2 is using a spike queue which B1 is not doing. Still, I think it may be the case that there are some inefficiencies there because it's uniformly slower in the second half run. You can also clearly see the N^2 construction cost hitting at large N (but let's deal with that separately).

Finally, here's NeuronGroup only but this time using exact integration:

figure_1

I'm not sure how fair this is given that with Anaconda you get an MKL-optimised matrix multiplication using all cores. On the other hand, this is the performance that a lot of users will see I guess.

Haven't looked at the code yet, but will do that later. What do you think about the ``SpikeMonitor`` and access to ``t`` issue?

Will also do more comprehensive comparisons using weave, cython, etc. and report on issue #446 but that doesn't affect whether or not this PR can merge.

**Comment by thesamovar** [comment]
OK I messed that last comment up a bit. I misread the refractoriness one: actually performance is a lot worse with refractoriness on for B2 than B1. That might be specific to the numpy target but we'll need to check that. Possibly it's worth paying this cost in order to get refractoriness right.

Also, I missed out the plot with synapses. Here it is:

figure_1

**Comment by mstimberg** [comment]
Maybe to clarify: I did not look at all at the performance of the code objects itself, but only at the preparation time and run loop overhead. So it might well be possible that there is some inefficiency in numpy specifically, so far we were always more concerned with the weave/cython performance (apart from the whole `ufunc.at` improvement).

**Comment by mstimberg** [comment]
Oh, not sure whether this changes anything but if I am not mistaken, the correct equivalent to the Brian 1 code with refractoriness is to only mark `v` as `unless refractory`, and not `ge` and `gi` as well as in the `compare_to_brian1` script.

**Comment by thesamovar** [comment]
With just one variable being refractory, here is the plot:

figure_1

So not quite as bad, but still slower. I think probably worth it for being correct.

**Comment by thesamovar** [comment]
Just checked and number of threads that the MKL uses doesn't change the total runtime (verified that it does change the number of threads being used by monitoring CPUs).

**Comment by mstimberg** [comment]
Just a quick remark about my last commit: there was a weird error in one of the tests when run with openmp. It happened on Mac OS with python 3, but the same problem arose at least once before and that time it was Linux with python 2... It is quite curious, since none of the relevant code objects is actually using openmp parallellization, so I have no idea what is going on there. I added some output to the test so that it will give more information when it fails again, but until then I don't really know what to do about it...

**Comment by mstimberg** [comment]
I had a quick look at why the exact integration is so slow. There is of course still the issue that in Brian 1, we calculate everything for the numerical values of all constants whereas in Brian 2, we do it symbolically (even a bit to the extreme, where the generated code still contains `mvolt`, etc. -- this is nice for readability but probably replacing it with the numerical values would be faster). But apart from that, we are generating very inefficient code for the state updater (it is about 25 times slower than the respective code in weave...). Here's what we do for updating v:
```Python
_v = (El + ((((_lio_3 * (((ge * (_lio_4 + exp(_lio_5 * int(not_refractory)))) * int(not_refractory)) * exp(_lio_6 * int(not_refractory)))) / (_lio_7 + (taue * int(not_refractory)))) + ((_lio_8 * (((gi * (_lio_9 + exp(_lio_5 * int(not_refractory)))) * int(not_refractory)) * exp(_lio_6 * int(not_refractory)))) / (_lio_7 + (taui * int(not_refractory))))) + (v * exp(_lio_6 * int(not_refractory))))) - (El * exp(_lio_6 * int(not_refractory)))
```
This evaluates not only `int(not_refractory)` but also more complex expressions like `exp(_lio_6*int(not_refractory)` several times (we don't have this issue in C since we now handle boolean expressions differently). One relatively simple solution would be to use sympy's CSE identification. I tried this out and it does not seem to be too heavy in computation (it adds 0.2s to the code generation process on my machine) and it speeds up the code considerably, by a factor of 2. The new code looks like this:
```Python
_cse_v0 = int(not_refractory)
_cse_v1 = exp(_cse_v0 * _lio_6)
_cse_v2 = exp(_cse_v0 * _lio_5)
_cse_v3 = _cse_v0 * _cse_v1
_v = (((((- El) * _cse_v1) + El) + (_cse_v1 * v)) + ((((_cse_v3 * _lio_3) * ge) * (_cse_v2 + _lio_4)) / ((_cse_v0 * taue) + _lio_7))) + ((((_cse_v3 * _lio_8) * gi) * (_cse_v2 + _lio_9)) / ((_cse_v0 * taui) + _lio_7))
```
What do you think? It is worth including, right?

**Comment by mstimberg** [comment]
I realized that there is one annoying issue that we did not take yet care of. In the work you did for the code optimization, we avoided incorrectly simplifying expressions that involved stateful functions. Unfortunately, we can't control this whenever we use sympy. In the current code, including `rand() - rand()` somewhere in equations will be simplified away directly. The changed I proposed above (extracting common subexpressions) would mean that we are using sympy for *all* statements, so this problem would also occur for code in `run_regularly` operations, in resets, etc. I guess we have to deal with this at the very first stage where we convert strings into sympy objects, but unfortunately this also means that we will need the `variables` dictionary there whereas currently we don't.

**Comment by mstimberg** [comment]
What about merging this branch as it is (if you are fine with all the changes, of course)? I think the CSE extraction and the issue of the stateful functions is important enough to be discussed/merged on its own (and nothing with respect to it changed in this branch so far).

**Comment by thesamovar** [comment]
Agreed - this is good to go now and we can discuss the other issues separately. Could you copy your comment about state updaters to the new issue/pr? I think that's actually a regression in my code: when I improved LIO optimisation stuff in the cython performance branch, I also removed the optimisation that simplifies boolean expressions because it wasn't necessary in weave/cython - but that meant that numpy got slower. Could re-enable that, but CSE is also a good idea.

**Pull request merged**
