### PR TITLE
[MRG] Fix #608

### LINKED ISSUE #608: Incorrect results for stochastic equations with `(unless refractory)`
I don't have time to look at it right now, but there is a severe problem for stochastic differential equations with `(unless refractory)`. Test code:
```Python
np.random.seed(1234)
G = NeuronGroup(1, 'dx/dt = -x/second + xi/sqrt(second) : 1 (unless refractory)', refractory=1*ms)

mon = StateMonitor(G, 'x', record=0)

run(1*ms)
print mon.x[0]
print G.state_updater.abstract_code
```
For Brian 2.0b4, the output without and with `unless refractory` is:
```
[ 0.          0.00471435 -0.00719588  0.00713191  0.00400468 -0.00320161
  0.00567034  0.01426566  0.007899    0.00805517]
not_refractory = (t - lastspike) > 0.001000
xi = dt**.5 * randn()
_x = -dt*x/second + x + 1.0*xi/sqrt(second)
x = _x
```
and
```
[ 0.          0.00471435 -0.00719588  0.00713191  0.00400468 -0.00320161
  0.00567034  0.01426566  0.007899    0.00805517]
not_refractory = (t - lastspike) > 0.001000
xi = dt**.5 * randn()
_x = -dt*x*int(not_refractory)/second + x + xi*int(not_refractory)/sqrt(second)
x = _x
```
i.e. the values stay the same as they should. With current master, however, we get:
```
[ 0.          0.00471435 -0.00719588  0.00713191  0.00400468 -0.00320161
  0.00567034  0.01426566  0.007899    0.00805517]
not_refractory = (t - lastspike) > 0.001000
xi = dt**.5 * randn()
_x = -dt*x/second + x + 1.0*xi/sqrt(second)
x = _x
```
and
```
[  0.00000000e+00   4.71435164e-07  -7.19587674e-07   7.13191253e-07
   4.00468037e-07  -3.20160743e-07   5.67034214e-07   1.42656592e-06
   7.89899763e-07   8.05517145e-07]
not_refractory = (t - lastspike) > 0.001000
xi = dt**.5 * randn()
_x = dt*(xi/sqrt(second) - x/second)*int(not_refractory) + x
x = _x
```

I suspect I introduced the bug somewhere around or in this commit: adafd63e7

### PR DESCRIPTION
**Pull request by mstimberg**
This fixes the incorrect integration of stochastic differential equations with refractory period. The problem was that the `collect` function did not pull the symbol out of the equations if it was nested (as by the multiplication with `int(not_refractory)`). I fixed this by expanding the equations first and I also added an assertion into the function itself so that it will raise an error if the "non-stochastic part" still has a stochastic symbol in it.
A new test that I added also triggered a bug with Cython that was not triggered before: the boolean simplification creates code like this:
```Cython
        if not_refractory:
            v *= _lio_2
        else:
            v *= 1.0
```
and then because v is a "conditional write" write variable, this is wrapped in another `if not_refractory` which expects the following code to be just a single line so it ends up as:
```Cython
        if not_refractory:
            if not_refractory:
            v *= _lio_2
        else:
            v *= 1.0
```
I don't know what a good way is to fix this for real, but I did a minimal fix that at least makes the code compile, even though it is of course not optimal:
```Cython
        if not_refractory:
            if not_refractory:
                v *= _lio_2
            else:
                v *= 1.0
```

I'd be happy to merge it like this and to fix it properly later.

### CODE REVIEW

**Comment by thesamovar** [comment]
This looks good to me. One question, are we only expanding out for stochastic equations? Also, we wanted to avoid exanding everything out originally for performance reasons (subexpressions are typically reused) - will this change hurt that?

Appveyor is presumably failing for the standard reason? Should we fix that before merging here (just about to do that in the compare to brian 1 branch) or just assume that it's OK?

**Comment by mstimberg** [comment]
> One question, are we only expanding out for stochastic equations?

Yes, if there is no stochastic symbol in the equations, then we return directly. 

> Also, we wanted to avoid exanding everything out originally for performance reasons (subexpressions are typically reused) - will this change hurt that?

We don't deal with this yet, we are always substituting subexpressions at the moment (#412) and I don't think the change in this branch changes anything in that regard.

> Appveyor is presumably failing for the standard reason? Should we fix that before merging here (just about to do that in the compare to brian 1 branch) or just assume that it's OK?

Ah yes, I forgot that we did not merge that fix yet. I'm fine to wait until the merge of `compare_to_brian_1` -- but give me a moment before merging that branch, I now manage to at least sometimes reproduce the OpenMP problem I mention in my last comment.

**Comment by thesamovar** [comment]
Ah yes, OK in that case I'm happy for this to be merged whenever.

For the compare to Brian 1 branch, I still have to make the change so that only OpenMP+MSVS2015 is disallowed. Will do that in a few minutes.

**Comment by thesamovar** [comment]
Do you want to go ahead and merge master into this and then hopefully it should pass tests and we can merge?

**Comment by mstimberg** [comment]
Yes, sure. Will do this in a minute.

**Comment by mstimberg** [comment]
We both agreed to merge this and all tests passed --> merging now.

**Pull request merged**
