### PR TITLE
[MRG] Fix scalar writes with OpenMP

### PR DESCRIPTION
**Pull request by mstimberg**
See discussion in #551, this puts the `parallel` pragma in individual templates instead of around the main run loop. This also means that by default everything will be executed serially, therefore there's no longer a need for the `IS_OPENMP_COMPATIBLE` flag in the templates (and much less `single` pragmas are necessary). I also updated the developer docs, mostly deleting things that are no longer applicable. I remember when @yger started implementing OpenMP support, we decided against doing it like this because it seemed to slow things down. However, I can't see any negative effect, possibly other things were responsible for the slow down.

Some quick-and-dirty benchmarks (median of three runs, everything normalized to a run without OpenMP (0.5 means 2x as fast), taking the output from the progress report, i.e. only runtime without synapse creation, compilation, etc.).

 | Before | after
-----------|----------|-------
IF_curve_Hodgkin_Huxley||
1 thread | 1.031 | 0.988
2 threads | 0.543 | 0.531
4 threads | 0.407 | 0.403
CUBA ||
1 thread | 1.000 | 1.000
2 threads | 0.607 | 0.629
4 threads | 0.652 | 0.652
STDP_standalone ||
1 thread | 1.524 | 1.439
2 threads | 1.788 | 1.814
4 threads | 2.140 | 2.137

So overall, OpenMP scaling is not great and is abyssimal for the STDP example where everything gets much slower instead of faster, but I don't see any significant differences before and after the changes from this pull request. Improving all of this is #539 

In the long run, we have even more flexibility with the new approach because you can use additional arguments to the `parallel` block to make variables thread-local, use reductions, etc.

### CODE REVIEW

**Comment by thesamovar** [comment]
Indeed I don't see any real speed difference so let's go with this. Is OpenMP tested comprehensively in our test suite? If so, I'm happy for this to be merged once they pass, otherwise I'll review the code a bit more carefully.

**Comment by mstimberg** [comment]
> Is OpenMP tested comprehensively in our test suite?

I would not say that... There's a single test `test_openmp_consistency` that uses a deterministic STDP example and looks for exact equivalence. And I added one more test for the specific scalar write issue. I'd say that our warning that OpenMP is not well tested still applies :-/

**Comment by thesamovar** [comment]
Oh yeah I forgot the warning. OK, so that's fine then. I think this can be merged when tests pass.

**Comment by mstimberg** [comment]
I did not quite like that OpenMP is not tested better so I added a new script `run_nose_tests_standalone_with_openmp` that runs the standalone test suite, but also runs all the standalone-compatible tests with OpenMP and 4 threads -- this should give us a bit more confidence that things are working correctly. The old `run_nose_tests_standalone` script will no longer run the two specific OpenMP tests. If all this passes, this should be good to merge (if you don't want to have a closer look at the code before).

**Comment by thesamovar** [comment]
Great! Merging now.

**Pull request merged**
