### PR TITLE
Add example for spike based homeostasis

### PR DESCRIPTION
**Pull request by schmitts**
An example for spike based homeostasis.

### CODE REVIEW

**Review by mstimberg — APPROVED** [review]
Many thanks for the example! I took the liberty to move it from "advanced" to the "synapses" category. Of course not because I consider it trivial, but simply because the "advanced" category  is used to showcase rarely used features while this example is using common Brian components. 
Thanks again!

**Comment by mstimberg** [comment]
Now rendered in the docs here: https://brian2.readthedocs.io/en/latest/examples/synapses.spike_based_homeostasis.html

**Comment by schmitts** [comment]
Thanks a lot. https://hub.gke2.mybinder.org/user/brian-team-brian2-binder-nhy68c2m/tree/examples/synapses/spike_based_homeostasis.ipynb not yet available?

**Comment by mstimberg** [comment]
> Thanks a lot. https://hub.gke2.mybinder.org/user/brian-team-brian2-binder-nhy68c2m/tree/examples/synapses/spike_based_homeostasis.ipynb not yet available?

The binder image only gets regenerated if the binder repository itself changes, so it does not get automatically triggered by the addition of new examples. Not quite sure what the best way to fix this would be... For now, I manually do empty dummy commits to trigger new images. I triggered a rebuild, so it should now work.

**Pull request merged**
