### PR TITLE
refactoring CPPStandaloneDevice

### PR DESCRIPTION
**Pull request by Kwartke**
fixes: #356 
Suggestions for other function names, further refactoring, ... are also welcome

### CODE REVIEW

**Comment by mstimberg** [comment]
Thanks, looks good to me! I'll wait for feedback from Dan, he might have had specific things in mind when opening the issue (he should be back from vacation next week).

**Comment by thesamovar** [comment]
Thanks for the PR!

The main point of the #356 was to make it easier to derive classes from CPPStandaloneDevice. I think the best way to see if this PR helps with that would be to look at a particular example, perhaps GeNN with @tnowotny.

**Comment by thesamovar** [comment]
OK so on looking at it in more detail, I think it looks good. Could you make just one change: the method ``check_OPENMP_compatible`` doesn't match our naming style: could you make it ``check_openmp_compatible``?

**Comment by thesamovar** [comment]
Thanks for making that change! I think this looks good now and it's passing the checks so I'm to go ahead and merge it.

Thanks again for the contribution!

**Pull request merged**
