### PR TITLE
Device correctness

### PR DESCRIPTION
**Pull request by thesamovar**
This branch isn't ready to merge yet, but I'm creating this pull request for discussion.

See issue #145.

### CODE REVIEW

**Comment by thesamovar** [comment]
Should we merge this branch at some point? It's not finished: more feature tests are needed, but the framework is OK I think? Not high priority, but I keep seeing this branch in the pull requests section...

**Comment by mstimberg** [comment]
I'd be happy to merge it now, adding feature tests is something that would also be ok to do by directly pushing to master, it can't break anything.

**Comment by thesamovar** [comment]
Unless we incorporate the feature tests into the test suite. ;)

**Comment by mstimberg** [comment]
Sure, but for that we need the more complex test setup, I don't think we are ever going to run them as part of the after-every-commit test suite on travis.

**Comment by thesamovar** [comment]
Indeed. OK shall I leave you to merge this then?

**Comment by mstimberg** [comment]
Doing the merge now. I'll leave the branch open, I think it's actually nicer if new tests and other related things are first added to this branch and then added in chunks to the master branch instead of directly adding them to master one by one. If the commits are only new tests and the like, feel free to directly merge into master however, no need for a pull request.

I'll also merge master into this branch so that it is up-to-date with the rest.

**Pull request merged**
