### PR TITLE
[MRG] Avoid sympy 1.1 for now

### PR DESCRIPTION
**Pull request by mstimberg**
Require sympy < 1.1 as a workaround for #856

### CODE REVIEW

**Comment by mstimberg** [comment]
Sympy got fixed in the meantime (the bug is only in 1.1.0, 1.1.1 has the fix), so I excluded the buggy version explicitly instead of requiring an older version. I also fixed another packaging issue: we were previously requiring an old version of scipy that still ships with weave, but this was no longer compatible with newer versions of numpy (or at least we did not have compatible packages). Instead, I'm now installing the standalone weave package (which is not part of anaconda itself but packages for conda-forge, I copied the packages to our brian-team channel).
I'll wait for the tests to pass and then merge, ok?

BTW: In the longer term we should probably get rid of our brian-specific channel and add Brian to conda-forge, this would also increase its visibility (not that important for Brian itself, but more so if we decide to finally split off `brian2.units` into its own package)

**Comment by thesamovar** [comment]
Yes to all that!

What do we need to do to get Brian into conda-forge? Does it imply any limitations?

**Comment by mstimberg** [comment]
> What do we need to do to get Brian into conda-forge? Does it imply any limitations?

It's quite straightforward, I did the same for a few packages already. The main limitation is that we can only depend on other packages in conda-forge, i.e. we lose the option to depend on specific packages that exist only in our own channel. I don't really think that's an issue anymore, since `py-cpuinfo` was the only package that we shipped ourselves, and I added it to conda-forge a while ago. Having it in conda-forge actually will also simplify our release procedure a bit, since we no longer upload the packages ourselves from travis/appveyor. Only downside I see at the moment: conda-forge does not build linux-32 packages. But then, for our latest Brian2 package, only 4 out of 1125 downloads were for linux-32, so we might as well drop those...

**Comment by thesamovar** [comment]
OK, yeah - let's do that then. Would make the installation even easier.

**Pull request merged**
