### PR TITLE
[GSoc2020] Improve report function in C++ standalone mode #1162

### PR DESCRIPTION
**Pull request by zeph1yr**
Added a time_format function to device.py and included <string> library to network.cpp that solves this issue.

### CODE REVIEW

**Comment by zeph1yr** [comment]
This commit fixes #1162

**Comment by mstimberg** [comment]
@zeph1yr  Thanks for the pull request, please let me know with a short comment whether you are still working on it or whether you consider it finished from your side. If it is basically finished, I'd start reviewing it.

**Comment by zeph1yr** [comment]
@mstimberg I have tested the implemented function and consider it finished from my side. Eagerly waiting it to be reviewed.

**Comment by mstimberg** [comment]
I tried out your code and noticed that the time formatting is only applied to the elapsed time, not to the estimated remaining time. Could you change that? I'll have a closer look at the details afterwards.

**Comment by zeph1yr** [comment]
@mstimberg A new PR is on it's way.

**Comment by zeph1yr** [comment]
@mstimberg Also there was a need to implement our own '''std::to_string''' function because "to_string not being part of std" was a known bug under MinGW which was later fixed and it depends on the compiler version. After trying to debug failed Travis CI build implementing my own function seemed to be a better choice.

**Comment by mstimberg** [comment]
> Also there was a need to implement our own '''std::to_string''' function because "to_string not being part of std" was a known bug under MinGW which was later fixed and it depends on the compiler version. 

This is interesting to know and would certainly have been a good reason for that approach in other contexts. However, we do not support MinGW under Windows, in our code we always assume the use of Visual Studio. 

>After trying to debug failed Travis CI build implementing my own function seemed to be a better choice.

Do you mean Appveyor? Travis CI is running under Linux and OS X. But even Appveyor should not use MinGW as explained above.

**Comment by mstimberg** [comment]
See my comment [here](https://github.com/brian-team/brian2/pull/1171#issuecomment-598303539), `std::to_string` should work correctly with older `gcc` versions if we pass `-std=c++11`.

**Comment by zeph1yr** [comment]
> Do you mean Appveyor? Travis CI is running under Linux and OS X. But even Appveyor should not use MinGW as explained above.
@mstimberg If I remember correctly, it was Travis CI build that failed and the environment was linux. The error pointed to to_string function and implementing my own function resolved the issue. 
An updated PR is on it's way.

**Comment by zeph1yr** [comment]
> See my comment [here](https://github.com/brian-team/brian2/pull/1171#issuecomment-598303539), `std::to_string` should work correctly with older `gcc` versions if we pass `-std=c++11`.

@mstimberg An updated PR is on it's way.


> Do you mean Appveyor? Travis CI is running under Linux and OS X. But even Appveyor should not use MinGW as explained above.

If I remember correctly it was Travis CI build that failed and the environment was Linux, also the error pointer to to_string function and implementing my own function resolved the issue. Anyways, thank you for the insight.

**Comment by mstimberg** [comment]
> If I remember correctly it was Travis CI build that failed and the environment was Linux, also the error pointer to to_string function and implementing my own function resolved the issue.

No, never mind, it did indeed fail on Linux (at least for some g++ versions). I was just confused because you mentioned MinGW which is a Windows-only software.

**Comment by mstimberg** [comment]
Apologies for the long delay in reviewing. I did not want to give further comments on PRs made as part of GSoC applications after the application deadline, to not give participants the false impression that this work was still taken into account for the application. I am going to close all "GSoC pull request" now, but of course we'd be more than happy to see you as a contributor in the future. Thanks again for your contribution!

**Pull request closed without merging**
