### PR TITLE
Implement generic typing for `_clip`

### PR DESCRIPTION
**Pull request by dsprenkels**
Issue: #782

This pull request makes a more abstract version of the `_clip` function
to accommodate also for arguments of other types than `double`.

It would probably be a good idea to add test cases for each of the different
types, but I have not really looked into the internals of your test suite yet.

### CODE REVIEW

**Comment by mstimberg** [comment]
Hi, thanks the changes look very good to me! A test would be good -- there's currently no way to define variables as anything else than double or int in model descriptions, so I think testing those two would be good enough for now.
To add a test, you can add a function called `test_clip` to `brian2.tests.test_functions`. Try to follow the example of something like `test_bool_to_int`, i.e. it should ideally:
* have a single run call + only check results after the run so that it runs with standalone mode (note that the run could potentially be `run(0*ms)` ).
* be annotated with the `standalone-compatible` attribute and use the `reinit_devices` teardown function.

More info on all this [here](http://brian2.readthedocs.io/en/latest/developer/guidelines/testing.html#unit-tests), but no need to delve deeply into it, adapting `test_bool_to_int` should be all you need.

To run the test suite on your machine, use one of the scripts in `dev/tools/tests`.

Many thanks in advance!

**Comment by dsprenkels** [comment]
During testing I found out that the Cython implementation was incorrect, because all the arguments and the return value used the same fused type. The argument types should of course be independent.

Now the `high`, `low` values need to be cast explicitly when they are returned to the caller.

**Comment by mstimberg** [comment]
> During testing I found out that the Cython implementation was incorrect, because all the arguments and the return value used the same fused type. The argument types should of course be independent.

Good catch! Do we really need independent fused types/templates for the `low`/`high` arguments, though? We care about preserving the type of the value that has been passed in, but `low` and `high` could simply be typed as double and C would automatically cast whatever type is passed in? So I think it would be enough to have the first argument as a fused type/template and make sure that the return value has the same type (by explicitly casting it to the type, if necessary).

**Comment by dsprenkels** [comment]
You're right. The other two fused types don't seem to be necessary. I changed the code accordingly.

**Comment by mstimberg** [comment]
Thanks! Sorry for nitpicking once more: I think for consistency it'd be the best if the C++ code also only used a template for the first argument.

**Comment by dsprenkels** [comment]
Updated the code.

One detail. Consider the following equation:

```
clipexpr1 = clip(integer_var1, 0, 1) : integer
```

This code uses integers for all types. But when the code is run, the runtime will perform an unnecessary cast four times (twice for `0`, twice for `1`; from and to `double`). This will probably happen very rarely, and the performance is probably negligible anyway, but it feels a bit weird to implement it this way.

**Comment by mstimberg** [comment]
Thanks again, this looks good to me, I'll just wait for the tests to run through before merging. I get your point about the unnecessary casts, but I think in this case I prefer simplicity over the (as you say, probably negligible) performance benefit. The most common use case is a double variable for the first value (then the other variables have to be cast to double for the comparison, anyway) and this should be fast, but integer variables are relatively rare. In your example, the profiler probably optimizes the problem away, anyway.

I'd be open to change this if profiling shows that it makes a measurable diference, though :-)

**Pull request merged**
