### PR TITLE
[MRG] Use filelock module

### LINKED ISSUE #1154: Investigate issues with parallel processes using Cython
According to a report on the [development mailing list](https://groups.google.com/d/topic/brian-development/FkeRd7BP9yM/discussion), running many simulations in parallel (with Cython) can sometimes lead to processes freezing. I'd say the most likely cause is a deadlock with the lock files we use to protect processes from trying to write to the same source files. In the [`filelock` branch](https://github.com/brian-team/brian2/tree/filelock), I replaced our own locking system by https://github.com/benediktschmitt/py-filelock , which seems to be a bit more mature and well-tested.
However, this does not seem to fix all issues.

### PR DESCRIPTION
**Pull request by mstimberg**
Even though it did not fix issue #1154 after all, I still think it is preferable to use the `filelock` module from https://github.com/benediktschmitt/py-filelock instead of our own solution. The approaches are basically the same, but the `filelock` module makes more effort to release locks in case of exceptions, etc. I included it directly in our utils package, since it is a single file and released into the Public Domain, so this seemed easier than adding a new dependency (it also allows us to downgrade the log level, otherwise we'd get messages about acquired/released locks by default...). 

This PR also documents the issue discussed in #1154, and I'd therefore say it closes #1154.

### CODE REVIEW

**Comment by thesamovar** [comment]
Does including a copy mean that we won't benefit from any updates? Maybe preferable to have it as a dependency if it's pure Python?

**Comment by mstimberg** [comment]
> Does including a copy mean that we won't benefit from any updates? Maybe preferable to have it as a dependency if it's pure Python?

I agree in principle, but there is the issue of pylock's logger that logs acquire/release messages as INFO messages (which we display by default). We'd have to somehow work around this issue if we don't use our own version. The last commit was 9 month ago, so it does not seem to change a lot anyway.

**Comment by thesamovar** [comment]
Yeah and looking at the code it's pretty short. Maybe set up an alert for when they release new versions so we can remember to include changes?

**Comment by thesamovar** [comment]
Although actually, is there no way to capture logs from another package and redefine them at a different level? I would have thought you could do that.

**Comment by mstimberg** [comment]
>  Maybe set up an alert for when they release new versions so we can remember to include changes?

Yep, I activate the "watch releases" option on their repository :eyeglasses:

**Comment by mstimberg** [comment]
> Although actually, is there no way to capture logs from another package and redefine them at a different level? I would have thought you could do that.

You can easily filter log messages from other packages to suppress them, but I'm not sure how you'd change their log level. Probably you could write your own logging handler or something like that. I think we have the problem mostly because we catch all log messages (to format them consistently and send them to the log file), otherwise `filelock` would still use the default display level – we display info messages but the default is to only display warning messages.

Don't think it is worth messing with all this...

**Comment by thesamovar** [comment]
Fine by me! :)

**Pull request merged**
