### PR TITLE
[MRG] "constant over timestep" subexpressions

### PR DESCRIPTION
**Pull request by mstimberg**
This is a start for what we discussed in #720 and #721. I went for a simple approach where the "constant over one timestep" subexpressions are pulled out in the beginning and converted into the "parameter + run_regularly" approach. The advantage of this is that nothing "downstream" (codegen, etc.) does have to be aware of the difference -- I think it's too late in the 2.0 process for any other solution (e.g. one that would break other devices).

Still, there are a few open questions:
1. What names for the flags to use -- we did not finish this discussion in #720. For now, I went for "constant over dt" and "variable over dt" but I am still happy to be persuaded by better options. @romainbrette any opinion on that?
2. The "constant over dt" subexpressions are currently updated in the `before_groups` slot. For most uses that makes sense, but maybe `start` is a better choice? In a little test I used a `run_regularly` operation and realized that subexpressions are updated only afterwards which would be quite surprising. On the other hand, even with `start`, it would compete with the `run_regularly` operation. Maybe `before_start`? It sounds silly, but we do allow it.
3. Currently, we only evaluate subexpressions once per code block if the variables they refer to are not written to. This means that even when subexpressions are marked as "variable over dt" and use to time-dependent/stateful expressions, they are not updated. We could either update the code in `make_statements` and take time-/state-dependence into account or simply get rid of the caching. I'd prefer the latter as the code is already very complicated and I think the performance benefits from the caching are minimal.
4. I added the same mechanism also to `Synapses`, but there is a problem here: if you define a subexpression as "constant over dt", then it will be updated every time step, even though it may only be used in `on_pre`/`on_post` statements and/or in `event-driven` equations. On the other hand, I am not sure it is worth complicating things with explicit checks for that, since "constant over dt" is an explicit choice and you have workarounds (not use a subexpression at all...). It should be mentioned in the documentation, at least.

### CODE REVIEW

**Comment by thesamovar** [comment]
For the names, I agree with your reasoning in the previous post on #720. I like the general idea of "constant/variable over dt" but how about "timestep" instead of dt? It feels more semantically correct. We could also go with "during" instead of "over" but it's more to type and I think "over" is clear enough. I think that "variable" is a good enough antonym to constant in this case (no chance of confusing it with "a variable").

For the time slot, I think if our name "constant over timestep" it would be strange if it actually changed during the timestep. In that case, maybe "constant for dt" or "constant over dt" would be more sensible indeed. Perhaps this is an argument for using the "before_start" slot though. In general, it fits what I'd guess the semantics should be better. I don't have really strong feelings about this, but this (and several other things) make me think more and more that we should prioritise having an automatically generated "simulation description" (or "methods section") in plain text that describes precisely what was simulated. Another thing we might think about doing here is having a check that if a constant-over-dt variable is accessed in a timestep before it is initialised for that time step then we have a warning. I could actually imagine that we could have quite a useful/interesting system of checking which variables are accessed when, and testing for and warning about potential mistakes.

I'd be happy to get rid of the caching if indeed it doesn't make much of a difference to performance (but we should really check this). If it does make a difference, we can reconsider whether or not it's worth it anyway or if we need to complicate.

For Synapses, what about we give an info log statement or warning to the effect that it may be unnecessarily slowing down the simulation? I guess it's a very rare case anyway.

**Comment by mstimberg** [comment]
> For the names, I agree with your reasoning in the previous post on #720. I like the general idea of "constant/variable over dt" but how about "timestep" instead of dt? It feels more semantically correct. We could also go with "during" instead of "over" but it's more to type and I think "over" is clear enough. I think that "variable" is a good enough antonym to constant in this case (no chance of confusing it with "a variable").

Ok, I'll get some feedback about the name from the others during our team meeting this Friday. I agree that "timestep" is somewhat less technical but I am a bit worried that the whole flag becomes really long...

> For the time slot, I think if our name "constant over timestep" it would be strange if it actually changed during the timestep. In that case, maybe "constant for dt" or "constant over dt" would be more sensible indeed. Perhaps this is an argument for using the "before_start" slot though. In general, it fits what I'd guess the semantics should be better.

I am still not sure about this (again, I'll ask for feedback on Friday). I think `before_start` is the most "principled" choice, though. We could go for an alternative (and much more difficult to implement) choice to update the value at the first use during a time step but that does not quite feel right, either.

> I don't have really strong feelings about this, but this (and several other things) make me think more and more that we should prioritise having an automatically generated "simulation description" (or "methods section") in plain text that describes precisely what was simulated.

That would indeed be useful, a first step would be to give easy access to the schedule (#678).

> Another thing we might think about doing here is having a check that if a constant-over-dt variable is accessed in a timestep before it is initialised for that time step then we have a warning. I could actually imagine that we could have quite a useful/interesting system of checking which variables are accessed when, and testing for and warning about potential mistakes.

Again agreed, but I think this is some major (and therefore definitely post-2.0) work. This is more or less #126 I guess.

> I'd be happy to get rid of the caching if indeed it doesn't make much of a difference to performance (but we should really check this). If it does make a difference, we can reconsider whether or not it's worth it anyway or if we need to complicate.

Ok, I'll try to run some benchmarking for this.

> For Synapses, what about we give an info log statement or warning to the effect that it may be unnecessarily slowing down the simulation? I guess it's a very rare case anyway.

Yes, makes sense.

**Comment by mstimberg** [comment]
>> I'd be happy to get rid of the caching if indeed it doesn't make much of a difference to performance (but we should really check this). If it does make a difference, we can reconsider whether or not it's worth it anyway or if we need to complicate.
> 
> Ok, I'll try to run some benchmarking for this.

Um, I'm having some trouble coming up with non-contrived example for this. For all the examples we have, none is actually re-using a subexpression in a way that would make use of the caching (I raised an exception in the "subexpression can be re-used" code path and it was never triggered...).

**Comment by thesamovar** [comment]
It's true that the name is long, but on the other hand it'll be rarely used so I think it's OK.

For the example, don't some of the HH examples use subexpressions? I know they did in Brian 1 but maybe we rewrote them not to use this for B2?

**Comment by mstimberg** [comment]
> For the example, don't some of the HH examples use subexpressions? I know they did in Brian 1 but maybe we rewrote them not to use this for B2?

They do but all subexpressions are substituted when the state updater is applied, so the state update step does not deal with subexpressions at all. Even if it did (which is not trivial to get right: #412), the HH equations use each subexpression only once, so they wouldn't be affected by the caching.

**Comment by thesamovar** [comment]
OK, so let's drop the subexpression caching then!

**Comment by mstimberg** [comment]
> OK, so let's drop the subexpression caching then!

Ok, I'll do that.

Here's the feedback I got from @romainbrette and @yger during our meeting:

The `constant over dt` or `constant over timestep` is clear, no strong preference for either.
The opposite `variable over dt` is not clear -- we did not find any better alternative but eventually agreed on the following: given that we have a hard time thinking of a use case where the expression refers to a stateful function *and* you'd like it to be re-evaluated for each use, how about not offering an alternative at all? This means: 1) standard subexpressions are by default re-evaluated for each use but can be made fixed by using `(constant over dt)`. 2) subexpressions referring to stateful functions raise an error unless they use `(constant over dt)`.

What do you think about that solution? I'd say we should give it a try, if at some point we come across a convincing use case for "variable over dt" stateful subexpressions, we can always add a flag later. There's a straightforward workaround (define one subexpression for each use or do not use a subexpression in the first place) anyway.

Otherwise, updating in `before_start` makes sense and no clear opinion on whether we need a warning in the case of synapses. The example is quite contrived, maybe we don't actually have to bother.

**Comment by mstimberg** [comment]
Oh and not related to today's discussion but I realized that I currently I check whether the subexpression is "stateful or time-dependent" -- I don't think we actually need to care about time-dependence, though.

**Comment by mstimberg** [comment]
Sorry for the noise, I just realized another thing: if we go with the proposal that subexpressions that depend on stateful functions *have to be* "constant over dt", then the whole issue of updating the caching mechanism to handle "variable over dt" yet stateful subexpressions go away. We could therefore leave the caching code in place (I still wouldn't mind deleting it, but maybe leaving it untouched reduces the probability of breaking something with this PR).

**Comment by thesamovar** [comment]
OK I'm happy with that solution. On reflection, "constant over dt" might actually make more sense than "constant over timestep" if we were to allow setting it in slots other than before_start. Since it's also shorter, let's stick with that. In other words, what you're already doing seems perfect to me.

**Comment by mstimberg** [comment]
Ok, great. I made a few last changes, ready-to-merge from my side.

**Comment by thesamovar** [comment]
OK, I haven't reviewed the code as thoroughly as I'd like because it's rather complex and I'm a bit busy with other stuff at the moment, but I had a quick scan through. A couple of comments:

1. It looks like subexpression cacheing has been removed, right? (At least, there seems to be a whole bunch of deleted code about subexpression cacheing.) I'm actually happy with that because it removes a potential source of errors in difficult-to-foresee scenarios.
2. The documentation mentions that declaring a variable as constant over dt might be useful in a differential equation to force the use of the linear integrator. Is that correct? Are we actually using that information? Do we have an example of when this might happen?

**Comment by mstimberg** [comment]
> It looks like subexpression cacheing has been removed, right? (At least, there seems to be a whole bunch of deleted code about subexpression cacheing.) I'm actually happy with that because it removes a potential source of errors in difficult-to-foresee scenarios.

Yes, I removed it and I agree that it is better to leave it out until we see a clear need for it.

> The documentation mentions that declaring a variable as constant over dt might be useful in a differential equation to force the use of the linear integrator. Is that correct? Are we actually using that information? Do we have an example of when this might happen?

Yes, that's correct. It is actually documenting something that I mentioned a few times as a somewhat clumsy workaround in the mailing list. If `x` is preventing you from using a linear integration, then you can replace
```Python
group = NeuronGroup(..., '''
x = non_lin_fun(...) : 1
''', ...)
```
by
```Python
group = NeuronGroup(..., '''
x : 1
''', ...)
group.run_regularly('x = non_lin_fun(...)')
```

This is exactly how the `(constant over dt)` flag is implemented right now, i.e. the parameter + `run_regularly` approach is equivalent to:
```Python
group = NeuronGroup(..., '''
x = non_lin_fun(...) : 1 (constant over dt)
''', ...)
```

Of course it might well be that it would be simpler to just use e.g. Euler integration instead of this exact integration + stepwise approximation approach. There's however at least one use case where you don't have the choice: in `SpatialNeuronGroup`, the membrane current *has* to depend linearly on `v` -- the `constant over dt` mechanism can be useful there.

This approach has disadvantages for the readability of the generated code (in the state update code, you don't see what `x` actually stands for) but it makes it super-simple for e.g. the stateupdater to support those new subexpressions -- it simply does not know about them and therefore does not care.

**Comment by thesamovar** [comment]
OK I think this is good to merge. I'll let you do the honours, just in case there were any last minute changes you wanted to make.

**Comment by mstimberg** [comment]
Great. No last-minute changes, merging it now.

**Comment by ShanqMa** [comment]
Hey there,

I am currently working on a spatialneuron. And i want to add **independent** current noise **in different compartments**. But i find there is only "constant over dt" option if I use randn() state function to generate white noise, which means the noise in every timestep will be global then.
Below i showed my eqs and the I_noise is the variable that i want to evaluate everytime when it appears (i think the exact case of "variable over dt" in your previous discussion), I am wondering what can i do to make it variable over dt?

`eqs = '''
Im =I_noise + (EM-v)/rm + gNa * m**3 * h * (ENa-v) + (gK  * n**4 + gKA * z **3 * j + gKCa ) * (EK-v) + gCa * c**3 * (ECa-v)  : amp/meter**2 
I_noise = sigma*randn()*dt**-0.5 : amp/meter**2  (variable over dt)`

Thank you a lot in advance!

Best,
Shan

**Comment by mstimberg** [comment]
Hi @ShanqMa . The `constant over dt` flag means that the value of the subexpression stays constant over the duration of the time step. For `rand()` calls, it means they are only generated once and not repeatedly if multiple places reference the variable – but this is not the case in your equations, it only gets referenced once. There is therefore not a global value for all compartments (this would require the `shared` flag): with your above code (and using `constant over dt`), you will already get independent noise across compartments. Here's a simple example showing this:
```Python
from brian2 import *

eqs = ''' Im = I_noise : amp/meter**2
          I_noise = 1*nA/cm**2 * randn(): amp/meter**2 (constant over dt)'''
morpho = Cylinder(length=100*um, diameter=10*um, n=10)
# Huge Ri to make the compartments "unconnected"
neuro = SpatialNeuron(morpho, eqs, Ri=1*Mohm*cm)
mon = StateMonitor(neuro, 'v', record=True)
run(100*ms)
plt.plot(mon.t/ms, mon.v.T/mV)
plt.show()
```
noise_compartments

**Comment by ShanqMa** [comment]
@mstimberg Thanks a lot for your reply! You are right, I misunderstood the documentation there. and I should have checked the results by myself firstly. 

Actually I still have another question, in the below equation I want to add independent noise for different channels:
eqs = '''
Im = (EM-v)/rm + INa + IK + IKA + IKCa + ICa  : amp/meter**2 
INa= gNa * (m**3 * h+sigma***randn()***dt**-0.5) * (ENa-v) : amp/meter**2
IK= gK * (n**4+sigma***randn()***dt**-0.5) * (EK-v) : amp/meter**2
IKA= gKA * (z**3 * j +sigma***randn()***dt**-0.5)* (EK-v) : amp/meter**2
IKCa= gKCa * (EK-v) : amp/meter**2
ICa= gCa * (c**3+sigma***randn()***dt**-0.5) * (ECa-v): amp/meter**2'''
But I got the errors saying 

> contains more than one call of randn, this is currently not supported since randn is a stateful function and its multiple calls might be treated incorrectly (e.g."rand() - rand()" could be  simplified to "0.0").
How can I overcome this setting and use multiple stateful function?

Thank you so much again!

Best,
Shan

**Pull request merged**
